### ISSUE TITLE
老哥，你用这套6dof预测准吗？

### ISSUE THREAD

**Issue by guobaozi** [zstu-lly/6DVNET#1]
主要是旋转角的预测，你觉得准吗？用这套的lb得分可以透露吗？

**Comment by zstu-lly** [comment]
我觉得一般般，不是很准

**Comment by zstu-lly** [comment]
得分0.075

**Comment by guobaozi** [comment]
多谢，我在lb上用拼音看到你了...  你做了数据清洗了吗，我做了数据清洗，感觉数据提高分数提高的最大...基础的公共kelnel我改动不多...

**Comment by zstu-lly** [comment]
兄弟，加我微信lly19980726说
